version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "presigned-url-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iv5j7pjlu61j"
s3_prefix = "presigned-url"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

